import json
import textwrap
from models import TestConfig, ApiEndpoint, HttpMethod


def _format_headers(headers: dict | None) -> str:
    if not headers:
        return "{}"
    return json.dumps(headers, indent=12)


def _format_body(body: dict | None) -> str:
    if not body:
        return "None"
    return json.dumps(body)


def _method_call(ep: ApiEndpoint) -> str:
    method = ep.method.value.lower()
    body_str = _format_body(ep.body)
    headers_str = _format_headers(ep.headers)

    if ep.method in (HttpMethod.POST, HttpMethod.PUT, HttpMethod.PATCH):
        return (
            f'self.client.{method}(\n'
            f'                "{ep.path}",\n'
            f'                json={body_str},\n'
            f'                headers={headers_str},\n'
            f'                name="{ep.name}"\n'
            f'            )'
        )
    else:
        return (
            f'self.client.{method}(\n'
            f'                "{ep.path}",\n'
            f'                headers={headers_str},\n'
            f'                name="{ep.name}"\n'
            f'            )'
        )


def generate_locust_script(config: TestConfig) -> str:
    """Generate a complete locust script from a TestConfig."""

    task_methods = []
    for ep in config.endpoints:
        method_name = ep.name.lower().replace(" ", "_").replace("-", "_")
        call = _method_call(ep)
        task_methods.append(
            f"    @task({ep.weight})\n"
            f"    def {method_name}(self):\n"
            f"        with {call} as response:\n"
            f"            if response.status_code >= 400:\n"
            f"                response.failure(f\"Got status {{response.status_code}}\")\n"
        )

    tasks_block = "\n\n".join(task_methods)

    script = (
        "# Auto-generated Locust script\n"
        "# Generated by LocustForge API Testing Tool\n\n"
        "from locust import HttpUser, task, between\n"
        "import json\n\n\n"
        f"class LoadTestUser(HttpUser):\n"
        f'    host = "{config.base_url}"\n'
        f"    wait_time = between({config.think_time_min}, {config.think_time_max})\n\n"
        f"{tasks_block}\n"
    )

    return script
